erp5: check repozo backup before restoring it

diff --git a/stack/erp5/instance-zeo.cfg.in b/stack/erp5/instance-zeo.cfg.in
--- a/stack/erp5/instance-zeo.cfg.in
+++ b/stack/erp5/instance-zeo.cfg.in
@@ -144,6 +144,12 @@ input = inline: #!/bin/sh
   fi
   echo "Removing $zodb_path..."
   echo "Restoring $storage_name into $zodb_path..."
+  $repozo --verify --repository="$zodb_backup_directory/$storage_name"
+  CURRENT_EXIT_CODE=$?
+  if [ ! "$CURRENT_EXIT_CODE"="0" ]; then
+    EXIT_CODE="$CURRENT_EXIT_CODE"
+    echo "$storage_name Backup verification failed. Backup data is inconsistent."
+  fi
   $repozo --recover --output="$zodb_directory/$zodb_path" --repository="$zodb_backup_directory/$storage_name"
   CURRENT_EXIT_CODE=$?
   if [ ! "$CURRENT_EXIT_CODE"="0" ]; then
