stack/erp5: Enable requesting mariadb replication
Allow requesting a mariadb set-up to replicate another mariadb:
- bootstrap from a statically served backup file
- replicate from a primary mariadb

diff --git a/stack/erp5/instance-mariadb.cfg.in b/stack/erp5/instance-mariadb.cfg.in
--- a/stack/erp5/instance-mariadb.cfg.in
+++ b/stack/erp5/instance-mariadb.cfg.in
@@ -18,7 +18,9 @@
 {%   set ip = (ipv4_set | list)[0] -%}
 {%   set ip_as_host = ip -%}
 {% endif -%}
-{% set dash = parameter_dict['dash-location'] ~ '/bin/dash' %}
+{% set dash = parameter_dict['dash-location'] ~ '/bin/dash' -%}
+{% set replication = slapparameter_dict.get('replication', {}) -%}
+
 
 [{{ section('publish') }}]
 recipe = slapos.cookbook:publish.serialised
@@ -197,10 +199,6 @@ mysql_tzinfo_to_sql = ${binary-wrap-mysql_tzinfo_to_sql:wrapper-path}
 recipe = slapos.recipe.template:jinja2
 output = ${directory:services}/mariadb
 url = {{ parameter_dict['template-mysqld-wrapper'] }}
-context =
-  key defaults_file my-cnf:output
-  key datadir my-cnf-parameters:data-directory
-  key environ :environ
 environ =
   GRN_PLUGINS_PATH='${my-cnf-parameters:groonga-plugins-path}'
   ODBCSYSINI='${my-cnf-parameters:etc-directory}'
@@ -208,6 +206,128 @@ environ =
   {%- for variable in slapparameter_dict.get('environment-variables', ()) %}
   {{ variable }}
   {%- endfor %}
+context =
+  key defaults_file my-cnf:output
+  key datadir my-cnf-parameters:data-directory
+  key environ :environ
+{%- if replication %}
+  key initialisation mariadb-setup-replication:output
+{%- endif %}
+
+{%- if replication %}
+{% set bootstrap_url = replication['bootstrap-url'] -%}
+{% set primary = urllib_parse.urlsplit(replication['primary-url']) -%}
+[{{ section('mariadb-setup-replication') }}]
+recipe = slapos.recipe.template
+output = ${directory:bin}/${:_buildout_section_name_}
+mysqld = {{ parameter_dict['mariadb-location'] }}/bin/mysqld
+zcat = {{ parameter_dict['gzip-location'] }}/bin/zcat
+wget = {{ parameter_dict['wget-location'] }}/bin/wget
+head = {{ parameter_dict['coreutils_location'] }}/bin/head
+grep = ${binary-link:target-directory}/grep
+sed = ${binary-link:target-directory}/sed
+bootstrapfile = ${directory:mariadb-backup-full}/bootstrap.sql.gz
+inline =
+  #! {{ dash }}
+  set -eu
+  echo -n "Starting mariadb for backup restoration"
+  ${:mysqld} --defaults-file='${my-cnf:output}' --innodb-flush-method=nosync --skip-innodb-doublewrite --innodb-flush-log-at-trx-commit=0 --sync-frm=0 --slow-query-log=0 --skip-log-bin &
+  PID=$!
+  trap "kill $PID; wait; exit 1" EXIT
+  while true; do
+    if [ ! -e "/proc/$PID" ]; then
+      trap EXIT
+      echo "Service exited, check logs"
+      wait
+      exit 1
+    fi
+    test -e ${my-cnf-parameters:socket} && break
+    echo -n .
+    sleep 0.5
+  done
+
+  echo -n "Updating mariadb"
+  ${update-mysql:output}
+
+  echo "Fetching ${:bootstrapfile}"
+  ${:wget} -O ${:bootstrapfile} {{ bootstrap_url }}
+
+  echo "Importing ${:bootstrapfile}"
+  ${:zcat} ${:bootstrapfile} | ${binary-wrap-mysql:wrapper-path}
+
+  echo "Extracting GTID from backup"
+  SQL_SET_GTID=$(${:zcat} ${:bootstrapfile} | ${:head} -n 100 | ${:grep} "^--\s*SET GLOBAL gtid_slave_pos=" | ${:sed} "s/^--\s*//")
+  if [ -z "$SQL_SET_GTID" ]; then
+    echo "GTID not found in backup; aborting"
+    exit 1
+  fi
+  echo "Found GTID: $SQL_SET_GTID"
+
+  echo "Configuring server as replica"
+  ${binary-wrap-mysql:wrapper-path} -e "$SQL_SET_GTID"
+  ${binary-wrap-mysql:wrapper-path} -e "
+    CHANGE MASTER TO
+    MASTER_HOST='{{ primary.hostname }}',
+    MASTER_USER='{{ primary.username }}',
+    MASTER_PASSWORD='{{ primary.password }}',
+    MASTER_PORT={{ primary.port }},
+    MASTER_USE_GTID="slave_pos";
+  "
+  ${binary-wrap-mysql:wrapper-path} -e "START SLAVE;"
+
+  echo "Stopping mariadb..."
+  trap EXIT
+  kill $PID
+  wait
+
+  echo "Done. Starting mariadb normally."
+
+{% set threshold = replication.get('seconds-behind-master-threshold', 0) -%}
+{% set primary = urllib_parse.urlsplit(replication['primary-url']) -%}
+[mariadb-replication-test]
+recipe = slapos.recipe.template
+output = ${directory:bin}/${:_buildout_section_name_}
+inline =
+  from contextlib import closing
+
+  from zope.interface import implementer
+  from slapos.grid.promise import interface
+  from slapos.grid.promise.generic import GenericPromise
+
+  import pymysql.cursors
+
+  max_delay = {{ int(replication.get('seconds-behind-master-threshold', 0)) }}
+
+  @implementer(interface.IPromise)
+  class RunPromise(GenericPromise):
+    def sense(self):
+      conn = pymysql.connect(
+        read_default_file='${my-cnf:output}',
+        cursorclass=pymysql.cursors.DictCursor)
+      with closing(conn):
+        with closing(conn.cursor()) as cursor:
+          cursor.execute("SHOW SLAVE STATUS")
+          data = cursor.fetchone()
+      data = {k.encode('utf-8'): s for k, s in data.items()}
+      seconds_behind = data.get('Seconds_Behind_Master')
+      if seconds_behind is None:
+        from pprint import pformat
+        self.logger.error("Replication is in bad state:\n%s", pformat(data))
+        return
+      log = self.logger.info
+      msg, args = "%d seconds behind", (seconds_behind,)
+      if seconds_behind > max_delay:
+        log = self.logger.error
+      log(msg, *args)
+
+[{{ section('mariadb-replication-promise') }}]
+recipe = slapos.cookbook:promise.plugin
+eggs =
+  slapos.core
+  PyMySQL
+file = ${mariadb-replication-test:output}
+output = ${directory:plugins}/mariadb_replication.py
+{%- endif %}
 
 
 [{{ section('mariadb-backup-static-server-promise') }}]
