stack.erp5: Abort also if pidfile cannot be read.

diff --git a/stack/erp5/instance-mariadb-resiliency-after-import-script.sh.in b/stack/erp5/instance-mariadb-resiliency-after-import-script.sh.in
--- a/stack/erp5/instance-mariadb-resiliency-after-import-script.sh.in
+++ b/stack/erp5/instance-mariadb-resiliency-after-import-script.sh.in
@@ -23,7 +23,11 @@ update_executable='${update-mysql:output}'
 
 # Make sure mariadb is not already running
 if [ -e "$pid_file" ]; then
-  pid=$(cat "$pid_file") > /dev/null 2>&1
+  pid=$(cat "$pid_file")
+  if [ $? -ne 0 ]; then
+    echo "Cannot read Mariadb pidfile, assuming running. Aborting."
+    exit 1
+  fi
   if kill -0 "$pid"; then
     echo "Mariadb is already running with pid $pid. Aborting."
     exit 1
