stack/monitor: clean up some files before starting apache

diff --git a/stack/monitor/templates/template-monitor-httpd-wrapper.sh.in b/stack/monitor/templates/template-monitor-httpd-wrapper.sh.in
--- a/stack/monitor/templates/template-monitor-httpd-wrapper.sh.in
+++ b/stack/monitor/templates/template-monitor-httpd-wrapper.sh.in
@@ -1,9 +1,11 @@
 #!{{ dash_binary }}
 # BEWARE: This file is operated by slapos node
 # BEWARE: It will be overwritten automatically
+set -e
 
 pid_file="{{ pid_file }}"
 monitor_httpd_conf_file={{ monitor_httpd_conf }}
+to_delete_tmp_files="{{ to_delete_tmp_files }}"
 
 if [ -f "$pid_file" ]; then
     pid=$(cat "$pid_file")
@@ -30,6 +32,13 @@ if [ -f "$pid_file" ]; then
         echo "No process is running with PID $pid, removing the pid file"
         rm -f {{ pid_file }};
     fi
+fi
+
+if [ -n "$to_delete_tmp_files" ]; then
+  # This is used to clean upcgisocket files
+  # not deleted aftera server shutdown
+  echo "Cleaning tmp files $to_delete_tmp_files before running the server"
+  find `dirname -- "$to_delete_tmp_files"` -wholename "$to_delete_tmp_files" -delete
 fi
 
 exec {{ monitor_httpd_wrapper_path }} "$@"
