software/theia: Add import promise

diff --git a/software/theia/instance-import.cfg.in b/software/theia/instance-import.cfg.in
--- a/software/theia/instance-import.cfg.in
+++ b/software/theia/instance-import.cfg.in
@@ -104,6 +104,48 @@ template =
   --errorfile {{ errorfile }}
 
 
+# Add a promise to check that the import script has run
+# successfully and recently (at most 2 days ago).
+[promises]
+import-promises =
+  $${import-promise:name}
+
+[import-promise]
+<= monitor-promise-base
+module = check_command_execute
+name = resiliency-import-promise.py
+config-command = $${import-promise-script:rendered}
+
+[initial-import-exitcode-file]
+recipe = slapos.recipe.template:jinja2
+rendered = $${theia-import-script:exitcode-file}
+template = inline:0
+once = $${:rendered}
+
+[import-promise-script]
+recipe = slapos.recipe.template:jinja2
+rendered = $${directory:bin}/import-promise-script
+exitcode-file = $${initial-import-exitcode-file:rendered}
+context =
+  key exitcodefile :exitcode-file
+  key errorfile theia-import-script:error-file
+template =
+  inline:#!/bin/sh
+  if [ -z $(find {{ repr(exitcodefile) }} -mtime -2) ]
+  then
+    echo "ERROR import script last ran on " $(date -r {{ repr(exitcodefile) }})
+    exit 1
+  elif [ $( cat {{ repr(exitcodefile) }}) -ne 0 ]
+  then
+    echo "ERROR import script failed on " $(date -r {{ repr(exitcodefile) }})
+    cat {{ repr(errorfile) }}
+    exit 1
+  else
+    echo "OK import script last ran on " $(date -r {{ repr(exitcodefile) }})
+    exit 0
+  fi
+
+
 # Resilient connection parameters of import instance are published
 # through the resilient stack.
 # Extend resilient parameters with normal theia connection parameters
