peertube: maybe we don't need to check the pg query?

diff --git a/software/peertube/template-peertube-restore.sh.in b/software/peertube/template-peertube-restore.sh.in
--- a/software/peertube/template-peertube-restore.sh.in
+++ b/software/peertube/template-peertube-restore.sh.in
@@ -63,17 +63,17 @@ echo "Ready to check postgresql is running..."
 
 # initial db setup
 # ( first quering PG several times waiting a bit till postgresql is started and ready )
-tpgwait=5
-while true; do
-    pgtables="$(psql -c '\d' 2>&1)" && break
-    tpgwait=$(( $tpgwait - 1 ))
-    test $tpgwait = 0 && die "pg query problem"
-    echo "I: PostgreSQL is not ready (yet ?); will retry $tpgwait times..." 1>&2
-    sleep 1
-done
-echo "I: PostgreSQL ready." 1>&2
+# tpgwait=5
+# while true; do
+#     pgtables="$(psql -c '\d' 2>&1)" && break
+#     tpgwait=$(( $tpgwait - 1 ))
+#     test $tpgwait = 0 && die "pg query problem"
+#     echo "I: PostgreSQL is not ready (yet ?); will retry $tpgwait times..." 1>&2
+#     sleep 1
+# done
+# echo "I: PostgreSQL ready." 1>&2
 
-sleep 5
+# sleep 5
 
 # Check the postgresql is running, if postgresql has stopped, abort
 pid_file=$${postgresql:pgdata-directory}/postmaster.pid
