Fix getting network info, prevent offline install and use SSL for NoVNC

diff --git a/software/openstack/templates/stack_controller_grizzly.sh.in b/software/openstack/templates/stack_controller_grizzly.sh.in
--- a/software/openstack/templates/stack_controller_grizzly.sh.in
+++ b/software/openstack/templates/stack_controller_grizzly.sh.in
@@ -6,6 +6,24 @@
 
 export DEBIAN_FRONTEND=noninteractive
 
+###############################################################################################
+#####  Check Installation and internet connexion
+###############################################################################################
+if [ -f .installed ]; then
+    echo "An installation of openstack already exist. Exiting..."
+    exit 0;
+fi
+
+wget -q --tries=10 --timeout=20 http://google.com
+if [[ $? -eq 0 ]]; then
+    echo "OK: Succefully check internet connection with success. Go next ...";
+else
+    echo "ERROR:  We can't install openstack without internet connection. Please check it before retry installation...";
+    exit 1;
+fi
+
+###############################################################################################
+
 apt-get update
 apt-get upgrade -y
 apt-get dist-upgrade -y
@@ -33,8 +51,8 @@ then
     BCAST=`cat network.conf | cut -d: -f4`
 else
     GATEWAY=`route | grep default | awk '{print $2}'`
-    MASK=`ifconfig eth0 | grep 'inet adr:' |  awk '{ print $4}' | cut -d: -f2`
-    BCAST=`ifconfig eth0 | grep 'inet adr:' |  awk '{ print $3}' | cut -d: -f2`
+    MASK=`ifconfig eth0 | egrep '(inet ad)d?r:' |  awk '{ print $4}' | cut -d: -f2`
+    BCAST=`ifconfig eth0 | egrep '(inet ad)d?r:' |  awk '{ print $3}' | cut -d: -f2`
     IPv4=`ip addr show eth0 | grep 'inet ' | awk '{print $2}' | cut -d/ -f1`
     echo "$IPv4:$MASK:$GATEWAY:$BCAST" > network.conf
 fi
@@ -118,6 +136,11 @@ EOF
 
 source localrc
 CURRENT_DIR=`pwd`
+VNC_BASE="${:vnc-frontend}"
+if [ -z "$VNC_BASE" ]; then
+    VNC_BASE=https://$PUBLIC_ADDRESS:6080
+fi
+
 
 ###############################################################################################
 #####  Install Mysql, ntp, MysqlDB and RabbitMQ
@@ -410,6 +433,16 @@ cp $CONF $CONF.orig
 	-e "s/%SERVICE_PASSWORD%/$ADMIN_PASSWORD/" \
 	-e "s/^#signing_dir *=.*/signing_dirname = \/tmp\/keystone-signing-nova/" \
 	$CONF.orig > $CONF
+  
+#Generate certificate to use for nova
+cd $CURRENT_DIR
+chmod +x generate_cert.py
+mkdir -p /etc/nova/ssl
+./generate_cert.py /etc/nova/ssl nova
+chown -R nova: /etc/nova/ssl
+chmod -R 700 /etc/nova/ssl
+
+#Configure nova
 
 CONF=/etc/nova/nova.conf
 cp $CONF $CONF.orig
@@ -436,7 +469,10 @@ image_service=nova.image.glance.GlanceImageService
 
 # Vnc configuration
 novnc_enabled=true
-novncproxy_base_url=http://$PUBLIC_ADDRESS:6080/vnc_auto.html
+ssl_only=true
+cert=/etc/nova/ssl/nova.crt
+key=/etc/nova/ssl/nova.key
+novncproxy_base_url=$VNC_BASE/vnc_auto.html
 novncproxy_port=6080
 vncserver_proxyclient_address=$HOST_IP
 vncserver_listen=0.0.0.0
@@ -648,3 +684,6 @@ nova --no-cache secgroup-add-rule default icmp -1 -1 0.0.0.0/0
 nova --no-cache secgroup-add-rule default tcp 22 22 0.0.0.0/0
 
 quantum floatingip-create ext_net
+
+#End Installation ...
+echo "done" > $CURRENT_DIR/.installed
